-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 09:32:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_concesionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_concesionario` DEFAULT CHARACTER SET utf8 ;
USE `db_concesionario` ;

-- -----------------------------------------------------
-- Table `db_concesionario`.`T_fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_concesionario`.`T_fabricante` (
  `id_fabricante` INT NOT NULL AUTO_INCREMENT,
  `nombre_fabricante` VARCHAR(45) NULL,
  PRIMARY KEY (`id_fabricante`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_concesionario`.`T_coches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_concesionario`.`T_coches` (
  `id_coches` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NULL,
  `fabricante` INT NULL,
  `foto` LONGBLOB NULL,
  `año` YEAR NULL,  
  PRIMARY KEY (`id_coches`),
  INDEX `id_fabricante_idx` (`fabricante` ASC),
  CONSTRAINT `id_fabricante`
    FOREIGN KEY (`fabricante`)
    REFERENCES `db_concesionario`.`T_fabricante` (`id_fabricante`)
    ON DELETE CASCADE  
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
